### ISSUE TITLE
docs: add list of possible WG_DECISION_URL

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec-w3c-auto-publish#12]
From https://github.com/w3c/respec-w3c-auto-publish/pull/11#discussion_r422023830

**Comment by marcoscaceres** [comment]
media-capture wg
https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0031.html

secondscreen wg
https://lists.w3.org/Archives/Public/public-secondscreen/2015Jun/0096.html

Web RTC
https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html

Aria
https://lists.w3.org/Archives/Public/public-html-admin/2015May/0021.html

device-apis
https://lists.w3.org/Archives/Public/public-device-apis/2015Oct/att-0037/minutes-2015-10-15.html#item05

**Comment by marcoscaceres** [comment]
Device APIs
https://lists.w3.org/Archives/Public/public-device-apis/2015Oct/att-0037/minutes-2015-10-15.html#item05
