### ISSUE TITLE
PUBLISH probably shouldn't be an option

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/respec-w3c-auto-publish#4]
As the name implies "w3c-auto-publish", I don't think it should be an option. It should always publish (after validation succeeds).

**Comment by sidvishnoi** [comment]
Only on merge though, right? I wanted to give users control when they want to publish. As the action might also be running on `pull_request`, I wanted to make sure it's published only when they intend to.
Should I use `github.event_name != 'pull_request'` as condition for publish by default and remove that option?

**Comment by marcoscaceres** [comment]
> Only on merge though, right? 

  yep

>  Should I use github.event_name != 'pull_request' as condition for publish by default and remove that option?

yeah, I  think that would  be best.
