### ISSUE TITLE
Move this repository to @W3C

### ISSUE THREAD

**Issue by sidvishnoi** [w3c/respec-w3c-auto-publish#9]
@siusin We would like to transfer ownership of this repository to the W3C organization. 
cc: @marcoscaceres

**Comment by siusin** [comment]
Thank you @sidvishnoi ! Sorry I missed this notification. Could you give me or anyone else in the W3C staff team the admin access to this repo, so that we can do the transfer?

**Comment by sidvishnoi** [comment]
Hi @siusin, I sent you invite as a collaborator. I couldn't find way to provide admin access. Let me know if collaborator access is enough for transfer.

**Comment by sidvishnoi** [comment]
Apparently no...
> There is only one owner of a repository owned by a user account; this permission cannot be shared with another user account.

> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

**Comment by marcoscaceres** [comment]
We might just need to copy/paste into a new repo. That’s ok tho.

**Comment by sidvishnoi** [comment]
GitHub user accounts don't allow admin access to anyone except the author. So, I moved this repository from my user account to an org account I have, and gave @siusin admin access there. Should be straightforward to transfer now.

Take that, GitHub!

**Comment by siusin** [comment]
Done! The repo is now under the W3C org, @sidvishnoi and the ReSpec Maintainers team own the admin access. Let me know if any further action is needed.

(feel free to remove my admin access to your org)

**Comment by sidvishnoi** [comment]
Thank you!
